### PR TITLE
Italian Translations

### PR DESCRIPTION
**Pull request by uzz75**

### CODE REVIEW

**Comment by RobertHeim** [comment]
Hey thank you, please update the errors: https://travis-ci.org/RobertHeim/phpbb3_1-ext-activitystats/jobs/52492714

**Comment by Hapek** [comment]
uzz75, 
1) you must delete one blank line at end of all four files.
2) In file activitystats.php, you must make "tab space" at lines 12 and 17 (delete spaces made by keyboard space)

**Comment by RobertHeim** [comment]
yeah, please commit it to this Pull Request, than it will be merged.

**Comment by uzz75** [comment]
Just correct the error.
But I can't found the "commit"

**Comment by RobertHeim** [comment]
Hey, there is still an error left: https://travis-ci.org/RobertHeim/phpbb3_1-ext-activitystats/jobs/52534425#L567

**Comment by uzz75** [comment]
I think it's ok
sorry for the time

**Comment by RobertHeim** [comment]
Hey, the error still persists. In file language/it/activitystats.php line 59 has additional whitespaces at the end of the line which must be deleted: https://travis-ci.org/RobertHeim/phpbb3_1-ext-activitystats/jobs/52534425#L567

**Comment by uzz75** [comment]
Ok.

Thanks For your support 

Inviato da iPhone

**Pull request merged**
