### PR TITLE
Updates for FRENCH translation for activitystats.php file + Fix for whitescreen on permissions page with FRENCH in ACP

### PR DESCRIPTION
**Pull request by Galixte**
Minor updates for FRENCH translation for activitystats.php file

### CODE REVIEW

**Comment by Galixte** [comment]
Are there any opposition to merge this pull ?

**Comment by RobertHeim** [comment]
yes, it will be merged, but it is not auto-mergable because of conflicts, so I need to get to my workstation first.

**Comment by Galixte** [comment]
OK it's my last commit: https://github.com/Galixte/phpbb3_1-ext-activitystats/commit/1667c751b849f611c3865d5689ba9f9ee18a9fad
Do you accept me to close this PR and i submit again in only two commits ?

**Comment by RobertHeim** [comment]
sure, do so!

**Pull request closed without merging**
